# Generated by Django 3.2.18 on 2023-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townhallselection',
            name='thumbnail',
            field=models.ImageField(upload_to='staticfiles/mediafiles/townhall/'),
        ),
    ]
